// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelShutdown():Promise<void>;

export function GetMetrics():Promise<Record<string, number>>;

export function GetSettings():Promise<main.SettingsDTO>;

export function GetStatus():Promise<main.StatusDTO>;

export function SaveSettings(arg1:main.SettingsDTO):Promise<void>;

export function StartMonitor():Promise<void>;

export function StopMonitor():Promise<void>;
