// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelShutdown() {
  return window['go']['main']['App']['CancelShutdown']();
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function StartMonitor() {
  return window['go']['main']['App']['StartMonitor']();
}

export function StopMonitor() {
  return window['go']['main']['App']['StopMonitor']();
}
