// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelShutdown():Promise<void>;

export function GetMetrics():Promise<Record<string, number>>;

export function StartMonitor():Promise<void>;

export function StopMonitor():Promise<void>;
